name: Close Issue on Task Completion

on:
  issues:
    types:
      - edited

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get issue body
        id: get_issue_body
        run: echo "ISSUE_BODY=$(jq -r .issue.body <<< '${{ github.event }}')" >> $GITHUB_ENV

      - name: Check if all tasks are completed
        run: |
          if [[ "${{ env.ISSUE_BODY }}" != *"- [ ]"* ]]; then
            echo "All tasks completed. Closing the issue."
            gh issue close ${{ github.event.issue.number }}
          else
            echo "There are still incomplete tasks. Issue will remain open."
